pipeline {
    agent any

    tools {
        jdk 'JDK17'
    }
    
    environment {
        PROJECT_DIR = 'com.example_SPA_CACHINA_jar_0.0.1-SNAPSHOT_3'
    }

    stages {
        stage('Inicio') {
            steps {
                echo 'Pipeline CI iniciado para La Cachina Fish'
                echo 'Sistema: Spring Boot + Thymeleaf + MySQL Aiven + Docker + Render'
            }
        }

        stage('Verificar estructura del proyecto') {
            steps {
                bat 'dir'
                bat "dir %PROJECT_DIR%"
                bat "if not exist %PROJECT_DIR%\\pom.xml exit /b 1"
                bat "if not exist %PROJECT_DIR%\\Dockerfile exit /b 1"
                bat "if not exist %PROJECT_DIR%\\mvnw.cmd exit /b 1"
            }
        }

        stage('Verificar entorno Jenkins') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat '''
                    echo ===== USUARIO DE JENKINS =====
                    whoami
                    echo USERPROFILE=%USERPROFILE%
                    echo JAVA_HOME=%JAVA_HOME%
        
                    echo ===== JAVA QUE USA JENKINS =====
                    java -version
                    where java
        
                    echo ===== MAVEN WRAPPER =====
                    mvnw.cmd -version
        
                    echo ===== VERIFICAR LOMBOK EN POM =====
                    findstr /i "lombok annotationProcessorPaths maven-compiler-plugin" pom.xml
        
                    echo ===== LOMBOK EN .M2 DE JENKINS =====
                    if exist "%USERPROFILE%\\.m2\\repository\\org\\projectlombok\\lombok" (
                        dir "%USERPROFILE%\\.m2\\repository\\org\\projectlombok\\lombok"
                    ) else (
                        echo NO EXISTE LOMBOK EN EL .M2 DEL USUARIO ACTUAL
                    )
        
                    if exist "C:\\Windows\\System32\\config\\systemprofile\\.m2\\repository\\org\\projectlombok\\lombok" (
                        dir "C:\\Windows\\System32\\config\\systemprofile\\.m2\\repository\\org\\projectlombok\\lombok"
                    ) else (
                        echo NO EXISTE LOMBOK EN SYSTEMPROFILE
                    )
                    '''
                }
            }
        }

        stage('Compilar con Maven') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'mvnw.cmd clean package -DskipTests'
                }
            }
        }

        stage('Validar JAR generado') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'dir target'
                }
            }
        }

        stage('Validar Dockerfile') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'type Dockerfile'
                }
                echo 'Dockerfile validado correctamente para despliegue en Render'
            }
        }

        stage('Pruebas de rendimiento con JMeter') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'if exist resultados-jmeter rmdir /s /q resultados-jmeter'
                    bat 'mkdir resultados-jmeter'
                    bat 'if not defined JMETER_HOME exit /b 1'
                    bat '"%JMETER_HOME%/bin/jmeter.bat" -n -t pruebas/jmeter/Pruebas_testeo_cachinafish.jmx -l resultados-jmeter/resultados.jtl -e -o resultados-jmeter/reporte-html'
                }
            }
        }

        stage('Resultado final') {
            steps {
                echo 'Pipeline CI completado. El proyecto queda validado para despliegue en Render.'
            }
        }
    }
}
