pipeline {
    agent any

    environment {
        PROJECT_DIR = 'com.example_SPA_CACHINA_jar_0.0.1-SNAPSHOT_3'
    }

    stages {
        stage('Inicio') {
            steps {
                echo 'Pipeline CI iniciado para La Cachina Fish'
                echo 'Sistema: Spring Boot + Thymeleaf + MySQL Aiven + Docker + Render'
            }
        }

        stage('Verificar estructura del proyecto') {
            steps {
                bat 'dir'
                bat "dir %PROJECT_DIR%"
                bat "if not exist %PROJECT_DIR%\\pom.xml exit /b 1"
                bat "if not exist %PROJECT_DIR%\\Dockerfile exit /b 1"
                bat "if not exist %PROJECT_DIR%\\mvnw.cmd exit /b 1"
            }
        }

        stage('Compilar con Maven') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'mvnw.cmd clean package -DskipTests'
                }
            }
        }

        stage('Validar JAR generado') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'dir target'
                }
            }
        }

        stage('Validar Dockerfile') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'type Dockerfile'
                }
                echo 'Dockerfile validado correctamente para despliegue en Render'
            }
        }

        stage('Pruebas de rendimiento con JMeter') {
            steps {
                dir("${env.PROJECT_DIR}") {
                    bat 'if exist resultados-jmeter rmdir /s /q resultados-jmeter'
                    bat 'mkdir resultados-jmeter'
                    bat '"C:\\Users\\David\\Downloads\\apache-jmeter-5.6.3\\apache-jmeter-5.6.3\\bin\\jmeter.bat" -n -t pruebas\\jmeter\\Pruebas_testeo_cachinafish.jmx -l resultados-jmeter\\resultados.jtl -e -o resultados-jmeter\\reporte-html'
                }
            }
        }

        stage('Resultado final') {
            steps {
                echo 'Pipeline CI completado. El proyecto queda validado para despliegue en Render.'
            }
        }
    }
}
